# -*- mode: python ; coding: utf-8 -*-


block_cipher = None
files = [

('logo/sg.png', '.'),
('logo/sg2.png', '.'),
('logo/sg3.png', '.'),
('logo/sg4.png', '.'),
('logo/sg5.png', '.'),
('logo/sg.ico', '.'),
('chinook.sqlite', '.'),
('conecta4/circulo_amarillo.png', '.'),
('conecta4/circulo_blanco.png', '.'),
('conecta4/circulo_rojo.png', '.'),
('fondo/fondo2.png', '.'),
('fondo/fondo2_2.png', '.'),
('fondo/fondo3.png', '.'),
('fondo/fondo4.png', '.'),
('battleship/agua.png', '.'),
('battleship/agua_fallo.png', '.'),
('battleship/fragmento_roto.png', '.'),
('battleship/agua - copia.png', '.'),
('hangman/fase1.png', '.'),
('hangman/fase2.png', '.'),
('hangman/fase3.png', '.'),
('hangman/fase4.png', '.'),
('hangman/fase5.png', '.'),
('hangman/fase6.png', '.'),
('hangman/fase7.png', '.'),
('hangman/fase8.png', '.'),
('blackjack/c1.png', '.'),
('blackjack/c2.png', '.'),
('blackjack/c3.png', '.'),
('blackjack/c4.png', '.'),
('blackjack/c5.png', '.'),
('blackjack/c6.png', '.'),
('blackjack/c7.png', '.'),
('blackjack/c8.png', '.'),
('blackjack/d1.png', '.'),
('blackjack/d2.png', '.'),
('blackjack/d3.png', '.'),
('blackjack/d4.png', '.'),
('blackjack/d5.png', '.'),
('blackjack/d6.png', '.'),
('blackjack/d7.png', '.'),
('blackjack/d8.png', '.'),
('blackjack/p1.png', '.'),
('blackjack/p2.png', '.'),
('blackjack/p3.png', '.'),
('blackjack/p4.png', '.'),
('blackjack/p5.png', '.'),
('blackjack/p6.png', '.'),
('blackjack/p7.png', '.'),
('blackjack/p8.png', '.'),
('blackjack/t1.png', '.'),
('blackjack/t2.png', '.'),
('blackjack/t3.png', '.'),
('blackjack/t4.png', '.'),
('blackjack/t5.png', '.'),
('blackjack/t6.png', '.'),
('blackjack/t7.png', '.'),
('blackjack/t8.png', '.'),
('blackjack/dorso.png', '.'),
('blackjack/dorso2.png', '.'),
('sonido/acierto.png', '.'),
('sonido/click.png', '.'),
('sonido/derrota.png', '.'),
('sonido/fallo.png', '.'),
('sonido/music.png', '.'),
('sonido/victoria.png', '.'),
('index.html', '.'),
('mycollection.qhc', '.'),
('resources.qrc', '.'),
]

a = Analysis(['simplegames_demo.py'],
             pathex=[],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts, 
          [],
          exclude_binaries=True,
          name='SimpleGames',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False,
		  icon='logo/sg.ico',
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas, 
               strip=False,
               upx=True,
               upx_exclude=[],
               name='SimpleGames')
